// eslint-disable-next-line no-restricted-imports
import * as colors from '../../do-not-export/colors';
import * as common from './common';

const dark = {
  BRAND_COLOR: common.BRAND_COLOR,
  BRAND_COLOR_ACTIVE: common.BRAND_COLOR_ACTIVE,
  BRAND_COLOR_DARK: common.BRAND_COLOR_DARK,
  BRAND_COLOR_LIGHT: common.BRAND_COLOR_LIGHT,
  FACEBOOK: common.FACEBOOK,
  GOOGLE: common.GOOGLE,
  INSTAGRAM: common.INSTAGRAM,
  LINKEDIN: common.LINKEDIN,
  TWITTER: common.TWITTER,
  YOUTUBE: common.YOUTUBE,

  // Globals
  GLOBAL_BACKGROUND: colors.BLACK_2,
  GLOBAL_COLOR: colors.GREY_2,
  GLOBAL_COLOR_2: colors.GREY_3,
  GLOBAL_COLOR_3: colors.GREY_5,

  FOOTER_BACKGROUND: colors.GREY_10,
  FOOTER_COLOR: colors.GREY_2,
  FOOTER_TEXT_SHADOW: colors.GRAY_TRASLUCENT,

  HEADER_BACKGROUND: colors.BRAND_COLOR_DARK,
  HEADER_COLOR: colors.WHITE_2,

  SIDEBAR_BACKGROUND: colors.GREY_10,
  SIDEBAR_BORDER: colors.GREY_9,
  SIDEBAR_COLOR: colors.GREY_2,
  SIDEBAR_SHADOW: colors.BLACK_TRASLUCENT,

  LANDING_BACKGROUND: colors.BRAND_COLOR_DARK,
  LANDING_COLOR: colors.GREY_2,

  // Statuses
  SUCCESS_BACKGROUND: colors.GREEN_4,
  SUCCESS_COLOR: colors.GREEN_1,

  WARNING_BACKGROUND: colors.YELLOW_2,
  WARNING_COLOR: colors.YELLOW_1,

  DANGER_BACKGROUND: colors.RED_3,
  DANGER_COLOR: colors.RED_1,

  INFO_BACKGROUND: colors.BRAND_COLOR_DARK,
  INFO_COLOR: colors.BRAND_COLOR,

  DISABLED_BACKGROUND: colors.GREY_7,
  DISABLED_BORDER: colors.GREY_5,
  DISABLED_COLOR: colors.GREY_4,

  ERROR_COLOR: colors.RED_2,
  SAVINGS_COLOR: colors.GREEN_3,

  // Avatar
  AVATAR_BACKGROUND: colors.GREY_10,
  AVATAR_BACKGROUND_EMPTY: colors.GREY_9,
  AVATAR_BORDER: colors.GREY_10,
  AVATAR_ICONS_COLOR: colors.GREY_8,

  // Card
  CARD_BACKGROUND: colors.GREY_10,

  // Filters
  FILTERS_BORDER: colors.GREY_8,

  // Message
  MESSAGE_BACKGROUND: colors.BRAND_COLOR_DARK,
  MESSAGE_COLOR: colors.BRAND_COLOR_LIGHT,

  // Modal
  BACKDROP_BACKGROUND: colors.BLACK_TRASLUCENT,

  // Spacer
  SPACER_BORDER: colors.GREY_5,

  // Table
  TABLE_BORDER: colors.GREY_4,

  // Tabs
  TAB_BACKGROUND: colors.GREY_9,
  TAB_BACKGROUND_ACTIVE: colors.GREY_10,
  TAB_BORDER: colors.BRAND_COLOR_DARK,
  TAB_COLOR: colors.WHITE_2,

  // Touchable
  BUTTON_BACKGROUND: colors.GREY_9,
  BUTTON_BACKGROUND_PRIMARY: colors.BRAND_COLOR,
  BUTTON_BORDER_PRIMARY: colors.BRAND_COLOR,
  BUTTON_COLOR: colors.WHITE_2,
  BUTTON_COLOR_PRIMARY: colors.BLACK_1,
  LINK_COLOR: colors.BRAND_COLOR,

  // Forms
  FIELD_BACKGROUND: colors.GREY_8,
  FIELD_BACKGROUND_ACTIVE: colors.BRAND_COLOR,
  FIELD_BORDER: colors.BRAND_COLOR_DARK,
  FIELD_COLOR: colors.GREY_2,
  FIELD_COLOR_ACTIVE: colors.GREY_8,

  // Checkbox
  CHECKBOX_BACKGROUND_ACTIVE: colors.BRAND_COLOR,
  CHECKBOX_TICK_COLOR: colors.GREY_8,

  // Date picker

  // Dropdown

  // Picture
  PICTURE_WRAPPER_BORDER: colors.GRAY_3,

  // Switch
  SWITCH_BACKGROUND: colors.GREY_8,
  SWITCH_SWITCHER_BACKGROUND: colors.GREY_10,
  SWITCH_SWITCHER_BACKGROUND_ACTIVE: colors.BRAND_COLOR,

  // Text

  // Shopping Cart
  CART_COLOR_DISCOUNT: colors.GREEN_2,
  CART_COLOR_BRAND: colors.GREY_5,

  // Loading
  LOADING_INDICATOR_BACKGROUND: colors.BRAND_COLOR_DARK,
  LOADING_INDICATOR_BAR: colors.WHITE_TRASLUCENT,

  // Payments
  PAYMENT_BACKGROUND: colors.BRAND_COLOR_DARK,
  PAYMENT_BACKGROUND_DEFAULT: colors.BRAND_COLOR,
  PAYMENT_BACKGROUND_NEW: colors.BLACK_2,
  PAYMENT_BORDER_NEW: colors.GRAY_3,
  PAYMENT_BORDER_NEW_HOVER: colors.GRAY_1,
  PAYMENT_COLOR: colors.BLACK_2,
  PAYMENT_COLOR_DEFAULT: colors.BLACK_1,
  PAYMENT_COLOR_NEW: colors.GRAY_3,
  PAYMENT_COLOR_NEW_HOVER: colors.GRAY_1,

  // Pricing
  PRICING_SHADOW: colors.BLACK_TRASLUCENT,
  PRICING_ICON_COLOR: colors.BRAND_COLOR,
  PRICING_COLOR: colors.GREY_3,
  PRICING_COLOR_DISCOUNT: colors.RED_3,
  PRICING_COLOR_HIGHLIGHT: colors.GREY_1,
  PRICING_COLOR_ORIGINAL: colors.GREY_5,
};

export default dark;
