type BRAND_COLOR = 'BRAND_COLOR';
type BRAND_COLOR_ACTIVE = 'BRAND_COLOR_ACTIVE';
type BRAND_COLOR_DARK = 'BRAND_COLOR_DARK';
type BRAND_COLOR_LIGHT = 'BRAND_COLOR_LIGHT';
type FACEBOOK = 'FACEBOOK';
type GOOGLE = 'GOOGLE';
type INSTAGRAM = 'INSTAGRAM';
type LINKEDIN = 'LINKEDIN';
type TWITTER = 'TWITTER';
type YOUTUBE = 'YOUTUBE';

// Globals
type GLOBAL_BACKGROUND = 'GLOBAL_BACKGROUND';
type GLOBAL_COLOR = 'GLOBAL_COLOR';
type GLOBAL_COLOR_2 = 'GLOBAL_COLOR_2';
type GLOBAL_COLOR_3 = 'GLOBAL_COLOR_3';

type FOOTER_BACKGROUND = 'FOOTER_BACKGROUND';
type FOOTER_COLOR = 'FOOTER_COLOR';
type FOOTER_TEXT_SHADOW = 'FOOTER_TEXT_SHADOW';

type HEADER_BACKGROUND = 'HEADER_BACKGROUND';
type HEADER_COLOR = 'HEADER_COLOR';

type SIDEBAR_BACKGROUND = 'SIDEBAR_BACKGROUND';
type SIDEBAR_BORDER = 'SIDEBAR_BORDER';
type SIDEBAR_COLOR = 'SIDEBAR_COLOR';
type SIDEBAR_SHADOW = 'SIDEBAR_SHADOW';

type LANDING_BACKGROUND = 'LANDING_BACKGROUND';
type LANDING_COLOR = 'LANDING_COLOR';

// Statuses
type SUCCESS_BACKGROUND = 'SUCCESS_BACKGROUND';
type SUCCESS_COLOR = 'SUCCESS_COLOR';

type WARNING_BACKGROUND = 'WARNING_BACKGROUND';
type WARNING_COLOR = 'WARNING_COLOR';

type DANGER_BACKGROUND = 'DANGER_BACKGROUND';
type DANGER_COLOR = 'DANGER_COLOR';

type INFO_BACKGROUND = 'INFO_BACKGROUND';
type INFO_COLOR = 'INFO_COLOR';

type DISABLED_BACKGROUND = 'DISABLED_BACKGROUND';
type DISABLED_BORDER = 'DISABLED_BORDER';
type DISABLED_COLOR = 'DISABLED_COLOR';

type ERROR_COLOR = 'ERROR_COLOR';
type SAVINGS_COLOR = 'SAVINGS_COLOR';

// Avatar
type AVATAR_BACKGROUND = 'AVATAR_BACKGROUND';
type AVATAR_BACKGROUND_EMPTY = 'AVATAR_BACKGROUND_EMPTY';
type AVATAR_BORDER = 'AVATAR_BORDER';
type AVATAR_ICONS_COLOR = 'AVATAR_ICONS_COLOR';

// Card
type CARD_BACKGROUND = 'CARD_BACKGROUND';

// Filters
type FILTERS_BORDER = 'FILTERS_BORDER';

// Message
type MESSAGE_BACKGROUND = 'MESSAGE_BACKGROUND';
type MESSAGE_COLOR = 'MESSAGE_COLOR';

// Modal
type BACKDROP_BACKGROUND = 'BACKDROP_BACKGROUND';

// Spacer
type SPACER_BORDER = 'SPACER_BORDER';

// Table
type TABLE_BORDER = 'TABLE_BORDER';

// Tabs
type TAB_BACKGROUND = 'TAB_BACKGROUND';
type TAB_BACKGROUND_ACTIVE = 'TAB_BACKGROUND_ACTIVE';
type TAB_BORDER = 'TAB_BORDER';
type TAB_COLOR = 'TAB_COLOR';

// Touchable
type BUTTON_BACKGROUND = 'BUTTON_BACKGROUND';
type BUTTON_BACKGROUND_PRIMARY = 'BUTTON_BACKGROUND_PRIMARY';
type BUTTON_BORDER_PRIMARY = 'BUTTON_BORDER_PRIMARY';
type BUTTON_COLOR = 'BUTTON_COLOR';
type BUTTON_COLOR_PRIMARY = 'BUTTON_COLOR_PRIMARY';
type LINK_COLOR = 'LINK_COLOR';

// Forms
type FIELD_BACKGROUND = 'FIELD_BACKGROUND';
type FIELD_BACKGROUND_ACTIVE = 'FIELD_BACKGROUND_ACTIVE';
type FIELD_BORDER = 'FIELD_BORDER';
type FIELD_COLOR = 'FIELD_COLOR';
type FIELD_COLOR_ACTIVE = 'FIELD_COLOR_ACTIVE';

// Checkbox
type CHECKBOX_BACKGROUND_ACTIVE = 'CHECKBOX_BACKGROUND_ACTIVE';
type CHECKBOX_TICK_COLOR = 'CHECKBOX_TICK_COLOR';

// Date picker

// Dropdown

// Picture
type PICTURE_WRAPPER_BORDER = 'PICTURE_WRAPPER_BORDER';

// Switch
type SWITCH_BACKGROUND = 'SWITCH_BACKGROUND';
type SWITCH_SWITCHER_BACKGROUND = 'SWITCH_SWITCHER_BACKGROUND';
type SWITCH_SWITCHER_BACKGROUND_ACTIVE = 'SWITCH_SWITCHER_BACKGROUND_ACTIVE';

// Text

// Shopping Cart
type CART_COLOR_DISCOUNT = 'CART_COLOR_DISCOUNT';
type CART_COLOR_BRAND = 'CART_COLOR_BRAND';

// Loading
type LOADING_INDICATOR_BACKGROUND = 'LOADING_INDICATOR_BACKGROUND';
type LOADING_INDICATOR_BAR = 'LOADING_INDICATOR_BAR';

// Payments
type PAYMENT_BACKGROUND = 'PAYMENT_BACKGROUND';
type PAYMENT_BACKGROUND_DEFAULT = 'PAYMENT_BACKGROUND_DEFAULT';
type PAYMENT_BACKGROUND_NEW = 'PAYMENT_BACKGROUND_NEW';
type PAYMENT_BORDER_NEW = 'PAYMENT_BORDER_NEW';
type PAYMENT_BORDER_NEW_HOVER = 'PAYMENT_BORDER_NEW_HOVER';
type PAYMENT_COLOR = 'PAYMENT_COLOR';
type PAYMENT_COLOR_DEFAULT = 'PAYMENT_COLOR_DEFAULT';
type PAYMENT_COLOR_NEW = 'PAYMENT_COLOR_NEW';
type PAYMENT_COLOR_NEW_HOVER = 'PAYMENT_COLOR_NEW_HOVER';

// Pricing
type PRICING_SHADOW = 'PRICING_SHADOW';
type PRICING_ICON_COLOR = 'PRICING_ICON_COLOR';
type PRICING_COLOR = 'PRICING_COLOR';
type PRICING_COLOR_DISCOUNT = 'PRICING_COLOR_DISCOUNT';
type PRICING_COLOR_HIGHLIGHT = 'PRICING_COLOR_HIGHLIGHT';
type PRICING_COLOR_ORIGINAL = 'PRICING_COLOR_ORIGINAL';

export type ColorName =
  | BRAND_COLOR
  | BRAND_COLOR_ACTIVE
  | BRAND_COLOR_DARK
  | BRAND_COLOR_LIGHT
  | FACEBOOK
  | GOOGLE
  | INSTAGRAM
  | LINKEDIN
  | TWITTER
  | YOUTUBE
  | GLOBAL_BACKGROUND
  | GLOBAL_COLOR
  | GLOBAL_COLOR_2
  | GLOBAL_COLOR_3
  | FOOTER_BACKGROUND
  | FOOTER_COLOR
  | FOOTER_TEXT_SHADOW
  | HEADER_BACKGROUND
  | HEADER_COLOR
  | SIDEBAR_BACKGROUND
  | SIDEBAR_BORDER
  | SIDEBAR_COLOR
  | SIDEBAR_SHADOW
  | LANDING_BACKGROUND
  | LANDING_COLOR
  | SUCCESS_BACKGROUND
  | SUCCESS_COLOR
  | WARNING_BACKGROUND
  | WARNING_COLOR
  | DANGER_BACKGROUND
  | DANGER_COLOR
  | INFO_BACKGROUND
  | INFO_COLOR
  | DISABLED_BACKGROUND
  | DISABLED_BORDER
  | DISABLED_COLOR
  | ERROR_COLOR
  | SAVINGS_COLOR
  | AVATAR_BACKGROUND
  | AVATAR_BACKGROUND_EMPTY
  | AVATAR_BORDER
  | AVATAR_ICONS_COLOR
  | CARD_BACKGROUND
  | FILTERS_BORDER
  | MESSAGE_BACKGROUND
  | MESSAGE_COLOR
  | BACKDROP_BACKGROUND
  | SPACER_BORDER
  | TABLE_BORDER
  | TAB_BACKGROUND
  | TAB_BACKGROUND_ACTIVE
  | TAB_BORDER
  | TAB_COLOR
  | BUTTON_BACKGROUND
  | BUTTON_BACKGROUND_PRIMARY
  | BUTTON_BORDER_PRIMARY
  | BUTTON_COLOR
  | BUTTON_COLOR_PRIMARY
  | LINK_COLOR
  | FIELD_BACKGROUND
  | FIELD_BACKGROUND_ACTIVE
  | FIELD_BORDER
  | FIELD_COLOR
  | FIELD_COLOR_ACTIVE
  | CHECKBOX_BACKGROUND_ACTIVE
  | CHECKBOX_TICK_COLOR
  | PICTURE_WRAPPER_BORDER
  | SWITCH_BACKGROUND
  | SWITCH_SWITCHER_BACKGROUND
  | SWITCH_SWITCHER_BACKGROUND_ACTIVE
  | CART_COLOR_DISCOUNT
  | CART_COLOR_BRAND
  | LOADING_INDICATOR_BACKGROUND
  | LOADING_INDICATOR_BAR
  | PAYMENT_BACKGROUND
  | PAYMENT_BACKGROUND_DEFAULT
  | PAYMENT_BACKGROUND_NEW
  | PAYMENT_BORDER_NEW
  | PAYMENT_BORDER_NEW_HOVER
  | PAYMENT_COLOR
  | PAYMENT_COLOR_DEFAULT
  | PAYMENT_COLOR_NEW
  | PAYMENT_COLOR_NEW_HOVER
  | PRICING_SHADOW
  | PRICING_ICON_COLOR
  | PRICING_COLOR
  | PRICING_COLOR_DISCOUNT
  | PRICING_COLOR_HIGHLIGHT
  | PRICING_COLOR_ORIGINAL;
